services:
  redis:
    image: "redis:8-alpine"
    container_name: "redis_broker"
    ports:
      - "6379:6379"
  redisInsight:
    image: "redislabs/redisinsight:latest"
    container_name: "redisinsight"
    ports:
      - "5540:5540"
    depends_on:
      - redis