services:
  db:
    image: "postgres:15-alpine"
    container_name: "ecommerce-db"
    environment:
      POSTGRES_DB : ${DB_NAME}
      POSTGRES_USER : ${DB_USER}
      POSTGRES_PASSWORD : ${DB_PASSWORD}
  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: "django_app"
    command: gunicorn ecommerce_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:8-alpine"
    container_name: "redis_broker"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: "celery_worker"
    command: celery -A ecommerce_app worker --loglevel=info
    environment:
      DATABASE_URL : ${DATABASE_URL}
      CELERY_BROKER_URL : ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND : ${CELERY_RESULT_BACKEND}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: "celery_beat"
    command: celery -A ecommerce_app beat --loglevel=info
    environment:
      DATABASE_URL : ${DATABASE_URL}
      CELERY_BROKER_URL : ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND : ${CELERY_RESULT_BACKEND}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx_app
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
  

volumes:
  postgres_data:
  static_volume:
  media_volume: